#!/bin/bash -l
#SBATCH --cluster=wice
#SBATCH --job-name=yahs_SW
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=128G
#SBATCH --time=12:00:00
#SBATCH --output=yahs_SW.%j.out
#SBATCH --error=yahs_SW.%j.err
#SBATCH --account=lp_svbelleghem

set -euo pipefail

# ============================================================
# YaHS scaffolding of the Pogonus chalceus SW assembly
# ============================================================

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

WORKDIR="/scratch/leuven/357/vsc35707/sw-assembly"
ASSEMBLY_DIR="${WORKDIR}/T2T_assembly"

REF="${ASSEMBLY_DIR}/purged.fa"

BAM_DIR="${WORKDIR}/HiC_mapping_SW/05_deduplicated_bams"
BAM="${BAM_DIR}/Pogonus_chalceus_SW_r.bam"

OUTDIR="${ASSEMBLY_DIR}/yahs_scaffolding"
TMPDIR="${OUTDIR}/tmp"

# YaHS output prefix
PREFIX="${OUTDIR}/Pchalceus_SW_yahs"

# Name-sorted BAM used by YaHS
NAME_SORTED_BAM="${OUTDIR}/Pogonus_chalceus_SW_r.namesort.bam"

# Final renamed assembly
FINAL_FASTA="${OUTDIR}/Pchalceus_SW.fa"
FINAL_AGP="${OUTDIR}/Pchalceus_SW.agp"

CPU="${SLURM_CPUS_PER_TASK:-32}"

# ------------------------------------------------------------
# YaHS parameters
# ------------------------------------------------------------

MAPQ=40
MIN_CONTIG_LENGTH=10000
ROUNDS=3

# ------------------------------------------------------------
# Activate environment
# ------------------------------------------------------------

source "/data/leuven/357/vsc35707/miniconda3/etc/profile.d/conda.sh"
conda activate thesis

unset PYTHONPATH
unset PYTHONHOME
export PYTHONNOUSERSITE=1

# ------------------------------------------------------------
# Create output directories
# ------------------------------------------------------------

mkdir -p "$OUTDIR" "$TMPDIR"

export TMPDIR

# ------------------------------------------------------------
# Job information
# ------------------------------------------------------------

echo "============================================================"
echo "YaHS scaffolding: Pogonus chalceus SW assembly"
echo "============================================================"
echo "Node:                   $(hostname)"
echo "Start time:             $(date)"
echo "Threads:                $CPU"
echo "Reference:              $REF"
echo "Coordinate-sorted BAM:  $BAM"
echo "Name-sorted BAM:        $NAME_SORTED_BAM"
echo "Output prefix:          $PREFIX"
echo "Minimum MAPQ:           $MAPQ"
echo "Minimum contig length:  $MIN_CONTIG_LENGTH"
echo "Rounds per resolution:  $ROUNDS"
echo

# ------------------------------------------------------------
# Check required programs
# ------------------------------------------------------------

for program in yahs samtools
do
    if ! command -v "$program" >/dev/null 2>&1; then
        echo "ERROR: Required program not found: $program" >&2
        exit 1
    fi
done

echo "Programs:"
echo "YaHS:     $(command -v yahs)"
echo "samtools: $(command -v samtools)"
echo

echo "YaHS version/help header:"
yahs 2>&1 | head -n 5 || true
echo

# ------------------------------------------------------------
# Check input files
# ------------------------------------------------------------

for file in "$REF" "$BAM"
do
    if [[ ! -s "$file" ]]; then
        echo "ERROR: Input file is missing or empty:" >&2
        echo "$file" >&2
        exit 1
    fi
done

echo "Input files:"
ls -lh "$REF" "$BAM"
echo

# ------------------------------------------------------------
# Check BAM integrity
# ------------------------------------------------------------

echo "============================================================"
echo "Checking input BAM integrity"
echo "============================================================"

samtools quickcheck -v "$BAM"

echo "Input BAM passed samtools quickcheck."
echo

# ------------------------------------------------------------
# Index reference assembly
# ------------------------------------------------------------

echo "============================================================"
echo "Checking reference FASTA index"
echo "============================================================"

if [[ ! -s "${REF}.fai" ]]; then
    echo "Creating FASTA index..."
    samtools faidx "$REF"
else
    echo "FASTA index already exists:"
    echo "${REF}.fai"
fi

echo

# ------------------------------------------------------------
# Name-sort BAM
#
# YaHS applies -q only when the BAM is sorted by read name.
# The BAM generated by the Arima pipeline is coordinate-sorted.
# ------------------------------------------------------------

echo "============================================================"
echo "Creating name-sorted BAM for YaHS"
echo "============================================================"

if [[ ! -s "$NAME_SORTED_BAM" ]]; then
    echo "Sorting BAM by read name..."
    echo "Start: $(date)"

    samtools sort \
        -n \
        -@ "$CPU" \
        -m 2G \
        -T "${TMPDIR}/Pchalceus_SW.namesort" \
        -o "${NAME_SORTED_BAM}.tmp" \
        "$BAM"

    mv "${NAME_SORTED_BAM}.tmp" "$NAME_SORTED_BAM"

    echo "Name sorting completed: $(date)"
else
    echo "Name-sorted BAM already exists:"
    echo "$NAME_SORTED_BAM"
fi

samtools quickcheck -v "$NAME_SORTED_BAM"

echo
echo "Name-sorted BAM:"
ls -lh "$NAME_SORTED_BAM"
echo

# Confirm the BAM sort order recorded in the header
echo "BAM header sort order:"
samtools view -H "$NAME_SORTED_BAM" |
    awk -F '\t' '$1 == "@HD" {print}'

echo

# ------------------------------------------------------------
# Avoid accidental overwriting
# ------------------------------------------------------------

if [[ -e "${PREFIX}_scaffolds_final.fa" ]] ||
   [[ -e "${PREFIX}_scaffolds_final.agp" ]]; then

    echo "ERROR: Existing YaHS output detected:" >&2
    echo "${PREFIX}_scaffolds_final.fa" >&2
    echo "${PREFIX}_scaffolds_final.agp" >&2
    echo >&2
    echo "Move or delete the existing output before rerunning." >&2
    exit 1
fi

# ------------------------------------------------------------
# Run YaHS
# ------------------------------------------------------------

echo "============================================================"
echo "Running YaHS"
echo "============================================================"
echo "Start: $(date)"

yahs \
    -o "$PREFIX" \
    -q "$MAPQ" \
    -l "$MIN_CONTIG_LENGTH" \
    -R "$ROUNDS" \
    "$REF" \
    "$NAME_SORTED_BAM"

echo "YaHS finished: $(date)"
echo

# ------------------------------------------------------------
# Check expected YaHS outputs
# ------------------------------------------------------------

YAHS_FASTA="${PREFIX}_scaffolds_final.fa"
YAHS_AGP="${PREFIX}_scaffolds_final.agp"
YAHS_BIN="${PREFIX}.bin"

for file in "$YAHS_FASTA" "$YAHS_AGP"
do
    if [[ ! -s "$file" ]]; then
        echo "ERROR: Expected YaHS output is missing or empty:" >&2
        echo "$file" >&2
        exit 1
    fi
done

# ------------------------------------------------------------
# Create consistently named final files
#
# Use symbolic links instead of mv so the original YaHS output
# names are retained.
# ------------------------------------------------------------

ln -sfn "$(basename "$YAHS_FASTA")" "$FINAL_FASTA"
ln -sfn "$(basename "$YAHS_AGP")" "$FINAL_AGP"

# ------------------------------------------------------------
# Index final scaffolded assembly
# ------------------------------------------------------------

echo "============================================================"
echo "Indexing final scaffolded assembly"
echo "============================================================"

samtools faidx "$YAHS_FASTA"

cut -f1,2 "${YAHS_FASTA}.fai" \
    > "${FINAL_FASTA}.genome"

# Also create a sequence-length table under the native YaHS name
cut -f1,2 "${YAHS_FASTA}.fai" \
    > "${PREFIX}_scaffolds_final.chrom.sizes"

# ------------------------------------------------------------
# Basic assembly statistics
# ------------------------------------------------------------

echo "============================================================"
echo "Basic scaffold statistics"
echo "============================================================"

awk '
BEGIN {
    n = 0
    total = 0
    max = 0
}
{
    n++
    total += $2
    if ($2 > max) {
        max = $2
    }
}
END {
    print "Number of sequences:", n
    print "Total assembly size:", total
    print "Longest scaffold:", max
}
' "${YAHS_FASTA}.fai"

echo

# ------------------------------------------------------------
# Final output summary
# ------------------------------------------------------------

echo "============================================================"
echo "YaHS scaffolding completed successfully"
echo "============================================================"
echo "End time: $(date)"
echo
echo "Native YaHS scaffold FASTA:"
echo "$YAHS_FASTA"
echo
echo "Native YaHS scaffold AGP:"
echo "$YAHS_AGP"
echo
echo "Final FASTA link:"
echo "$FINAL_FASTA"
echo
echo "Final AGP link:"
echo "$FINAL_AGP"
echo
echo "FASTA index:"
echo "${YAHS_FASTA}.fai"
echo
echo "Chromosome/scaffold sizes:"
echo "${PREFIX}_scaffolds_final.chrom.sizes"
echo
echo "YaHS BIN file, when generated:"
echo "$YAHS_BIN"
echo "============================================================"
