#!/bin/bash -l
#SBATCH --cluster=genius
#SBATCH --partition=bigmem_long
#SBATCH --job-name Pog_hifiasm
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --mem=1200G
#SBATCH --time=168:00:00
#SBATCH -o Pog_hifiasm.%j.out
#SBATCH -A lp_svbelleghem

#assembly
#homozygous coverage obtained from second peak of the k-mer plot (twice the heterozygous peak) generated by jellyfish
#purge max obtained from the third peak of the k-mer plot (twice the homozygous peak)
# For the SW individual, hom-cov = 88 and purge-max = 120
hifiasm -o Pogonus_T2T.asm --primary --n-hap 2 --hom-cov 88 -t 36 --ul nanopore/GC157812.fasta --ul-cut 20000 --h1 omnic/TTCCAAGG-CCTTGTAG_R1.fastq.gz --h2 omnic/TTCCAAGG-CCTTGTAG_R2.fastq.gz pacbio/bc2041.fastq.gz

awk '/^S/{print ">"$2;print $3}' Pogonus_T2T.asm.hic.p_ctg.gfa > Pogonus_T2T.asm.hic.p_ctg.fa

# Only with HiFi reads
hifiasm -o Pogonus_tidal_HiFi.asm --primary --n-hap 2 --hom-cov 88 -l 3 pacbio/bc2041.fastq.gz

awk '/^S/{print ">"$2;print $3}' Pogonus_tidal_HiFi.asm.hic.p_ctg.gfa > Pogonus_tidal_HiFi.asm.hic.p_ctg.fa
